/**
 * 
 * === Hydration ===
 * When we use Next.js, the server sends a static HTML "snapshot" to the browser.
 * Then, React "wakes up" in the browser and tries to attack event listeners to that HTML.
 * This process is called Hydration.
 * 
 */


// MICROLAB
// A common bug in 2026 is trying to access window or localStorage during the SSR phase.
// Since the server has no "window", our app crashes. We must learn to use the useEffect Mounting Pattern or dynamic imports.

import { useState, useEffect } from 'react';

export default function SafeComponent() {
    const [data, setData] = useState(null);

    useEffect(() => {
        // This code only runs on the CLIENT
        const saved = localStorage.getItem('user-settings');
        setData(saved);
    }, []);

    return <div>Settings: {data || "Loading..."}</div>
}

// Key Take-away:
// 1. If the above code is used in a NextJS application without useEffect(), the application will crash because Node.js server doesn't have a "browser window" or "localStorage". useEffect() make sure the code within is run only on the client side.
// 2. Next.js expects the HTML generated by the server to match the first render on the client exactly.